arm_variant_type: # [aarch64]
  - sbsa          # [aarch64]

docker_image:                                          # [os.environ.get("BUILD_PLATFORM", "").startswith("linux")]
   - quay.io/condaforge/linux-anvil-comp7              # [linux64 and os.environ.get("BUILD_PLATFORM") == "linux-64"]
   - quay.io/condaforge/linux-anvil-cuda:11.2          # [linux64 and os.environ.get("BUILD_PLATFORM") == "linux-64"]
   - quay.io/condaforge/linux-anvil-aarch64-cuda:11.2  # [aarch64 and os.environ.get("BUILD_PLATFORM") == "linux-aarch64"]

c_compiler_version:     # [linux]
  - 7                   # [linux64]
  - 8                   # [ppc64le or aarch64]
cxx_compiler_version:   # [linux]
  - 7                   # [linux64]
  - 8                   # [ppc64le or aarch64]

cuda_compiler:   # [linux64 or aarch64 or win]
  - nvcc         # [linux64 or aarch64 or win]

cuda_compiler_version:
  - None
  - 11.2                       # [linux64 or aarch64 or win]

cudnn:
  - undefined
  - 8                          # [linux64 or win]
  - undefined                  # [aarch64]

cdt_name:  # [linux]
  - cos6   # [linux64]
  - cos7   # [linux64]
  - cos8   # [aarch64]

#zip_keys:
#  - - cudnn                      # [linux64 or win]
#    - cuda_compiler_version      # [linux64 or win]
#    - docker_image               # [linux64 and os.environ.get("BUILD_PLATFORM") == "linux-64"]
#    - cdt_name                   # [linux64]
