{% set version = "0.4.0.7" %}

package:
  name: cusparselt
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cusparselt/redist/libcusparse_lt/linux-x86_64/libcusparse_lt-linux-x86_64-{{ version }}-archive.tar.xz   # [linux64]
  url: https://developer.download.nvidia.com/compute/cusparselt/redist/libcusparse_lt/linux-sbsa/libcusparse_lt-linux-sbsa-{{ version }}-archive.tar.xz       # [aarch64]
  url: https://developer.download.nvidia.com/compute/cusparselt/redist/libcusparse_lt/windows-x86_64/libcusparse_lt-windows-x86_64-{{ version }}-archive.zip  # [win64]
  sha256: 15fc65cddcc76dceec41985a0737bc055c3944eadd02589ec8883f1196911f78  # [linux64]
  sha256: 866ee6cefb17d8041f099c6b43a731278721aa0ab682ddaa08886667a85495d6  # [aarch64]
  sha256: 09dc2e7b95da72f315cdd75a815e84b6c9bb9d01677f2837013fe6d57af616fd  # [win64]

build:
  number: 3
  skip: true  # [ppc64le or cuda_compiler_version not in ("11.2", "12.0")]
  script:
    # According to the cuSPARSE team, the same binary works for both CUDA 11 & 12
    - mkdir -p $PREFIX/include                                                # [unix]
    - cp -r include/* $PREFIX/include/                                        # [unix]
    - mkdir -p $PREFIX/lib                                                    # [unix]
    - mv lib/libcusparseLt.so* $PREFIX/lib/                                   # [unix]

    - copy include\\cusparseLt.h %LIBRARY_INC%\\                           # [win64]
    - copy lib\\cusparseLt.dll %LIBRARY_BIN%\\                             # [win64]
    - copy lib\\cusparseLt.lib %LIBRARY_LIB%\\                             # [win64]
  run_exports:
    - {{ pin_subpackage('cusparselt', exact=True) }}
  missing_dso_whitelist:
    - '*/libgomp.*'  # [linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - sysroot_linux-64 2.17  # [linux64]
  host:
    # https://github.com/NixOS/patchelf/issues/492
    - patchelf !=0.18     # [linux]
  run:
  run_constrained:
    # Only GLIBC_2.17 or older symbols present
    - __glibc >=2.17      # [linux]

test:
  requires:
    - git
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - sysroot_linux-64 2.17  # [linux64]
    # make sure we pick up the version matching the docker,
    # or the linker would complain
    - cudatoolkit 11.2|11.2.*       # [cuda_compiler_version == "11.2"]
    # tests need the cuSPARSE header
    - libcusparse-dev               # [cuda_compiler_version == "12.0"]
  files:
    - test_load_elf.c        # [linux]

about:
  home: https://developer.nvidia.com/cusparse
  license: LicenseRef-cuSPARSELt-Software-License-Agreement
  license_url: https://docs.nvidia.com/cuda/cusparselt/license.html
  license_file: LICENSE
  summary: "Basic Linear Algebra for Sparse Matrices on NVIDIA GPUs"
  description: |
    NVIDIA cuSPARSELt is a high-performance CUDA library dedicated to general
    matrix-matrix operations in which at least one operand is a sparse matrix.
    The cuSPARSELt APIs allow flexibility in the algorithm/operation selection,
    epilogue, and matrix characteristics, including memory layout,
    alignment, and data types.
    License Agreements:- The packages are governed by the NVIDIA cuSPARSELt
    Software License Agreement (EULA). By downloading and using the packages,
    you accept the terms and conditions of the NVIDIA cuSPARSELt EULA -
    https://docs.nvidia.com/cuda/cusparselt/license.html
  doc_url: https://docs.nvidia.com/cuda/cusparselt/index.html
  dev_url: https://developer.nvidia.com/cusparselt/downloads

extra:
  recipe-maintainers:
    - mnicely
    - leofang
