{% set version = "0.5.2.1" %}

package:
  name: cusparselt
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cusparselt/redist/libcusparse_lt/linux-x86_64/libcusparse_lt-linux-x86_64-{{ version }}-archive.tar.xz  # [linux64]
  url: https://developer.download.nvidia.com/compute/cusparselt/redist/libcusparse_lt/linux-sbsa/libcusparse_lt-linux-sbsa-{{ version }}-archive.tar.xz  # [aarch64]
  url: https://developer.download.nvidia.com/compute/cusparselt/redist/libcusparse_lt/windows-x86_64/libcusparse_lt-windows-x86_64-{{ version }}-archive.zip  # [win64]
  sha256: d6cd9ffc0838d2e25453358ca160c1bed34e2f7b5dc155c428d22ba7fc3d8334  # [linux64]
  sha256: 389167df60404fe9d49f5975239bd095c440328d951152082d8603f8bdac1a97  # [aarch64]
  sha256: ae4532cb17c55e224bb8c8f7786f1e115626571ba1843dcaf8bb67cfae12f613  # [win64]

build:
  number: 0
  skip: true  # [ppc64le or not cuda_compiler_version.startswith("12")]
  script:
    # According to the cuSPARSE team, the same binary works for both CUDA 11 & 12
    - mkdir -p $PREFIX/include                                                # [unix]
    - cp -r include/* $PREFIX/include/                                        # [unix]
    - mkdir -p $PREFIX/lib                                                    # [unix]
    - mv lib/libcusparseLt.so* $PREFIX/lib/                                   # [unix]

    - copy include\\cusparseLt.h %LIBRARY_INC%\\                           # [win64]
    - copy lib\\cusparseLt.dll %LIBRARY_BIN%\\                             # [win64]
    - copy lib\\cusparseLt.lib %LIBRARY_LIB%\\                             # [win64]
  run_exports:
    - {{ pin_subpackage('cusparselt', exact=True) }}
  missing_dso_whitelist:
    - '*/libgomp.*'  # [linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - sysroot_linux-64 2.17  # [linux64]
  host:
    # https://github.com/NixOS/patchelf/issues/492
    - patchelf !=0.18     # [linux]
  run:
  run_constrained:
    # Only GLIBC_2.17 or older symbols present
    - __glibc >=2.17      # [linux]

test:
  requires:
    - git
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - sysroot_linux-64 2.17  # [linux64]
    # tests need the cuSPARSE header & libnvrtc.so
    - libcusparse-dev
    - cuda-nvrtc-dev
  files:
    - test_load_elf.c        # [linux]

about:
  home: https://developer.nvidia.com/cusparse
  license: LicenseRef-cuSPARSELt-Software-License-Agreement
  license_url: https://docs.nvidia.com/cuda/cusparselt/license.html
  license_file: LICENSE
  summary: "Basic Linear Algebra for Sparse Matrices on NVIDIA GPUs"
  description: |
    NVIDIA cuSPARSELt is a high-performance CUDA library dedicated to general
    matrix-matrix operations in which at least one operand is a sparse matrix.
    The cuSPARSELt APIs allow flexibility in the algorithm/operation selection,
    epilogue, and matrix characteristics, including memory layout,
    alignment, and data types.
    License Agreements:- The packages are governed by the NVIDIA cuSPARSELt
    Software License Agreement (EULA). By downloading and using the packages,
    you accept the terms and conditions of the NVIDIA cuSPARSELt EULA -
    https://docs.nvidia.com/cuda/cusparselt/license.html
  doc_url: https://docs.nvidia.com/cuda/cusparselt/index.html
  dev_url: https://developer.nvidia.com/cusparselt/downloads

extra:
  recipe-maintainers:
    - mtjrider
    - mnicely
    - leofang
